<?php
$id=$_REQUEST['id'];
$name=$_REQUEST['name'];
$time=$_REQUEST['time'];
$isPeed=$_REQUEST['isPeed'];
$isPooped=$_REQUEST['isPooped'];
$isAte=$_REQUEST['isAte'];
$date=$_REQUEST['date'];
$isPeedInside=$_REQUEST['isPeedInside'];
$isPoopedInside=$_REQUEST['isPoopedInside'];
?>